### PR TITLE
Added a "log level" and a "close to tray" settings for the application

### PR DESCRIPTION
**Pull request by davidp57**
I added a LOG_LEVEL setting to the settings file, that can be :

- 0 : errors only
- 1 : errors, warnings
- 2 : errors, warnings, informations
- 3 : errors, warnings, informations, debug

I refactored the windows form a bit to add a combo box for selecting the log level.
It can be changed while the app is running and connected.
I did not add a command line option for the log level.

I also added a CLOSE_TO_TRAY setting, with a linked checkbox in the application.
If unchecked, clicking the "close" cross will do the same as the "quit" button ; if checked, minimize to tray.

### CODE REVIEW

**Comment by szporwolik** [comment]
Great thanks Sir! I will leave it open for a while, we will go with DLL and then integrate everything into Dev for testing.

**Comment by davidp57** [comment]
> Great thanks Sir!

You're most welcome !

> we will go with DLL and then integrate everything into Dev for testing.

What do you mean with "go with DLL" ?

**Comment by szporwolik** [comment]
Well as mentioned in #50 - there is a person, who tries to move the communication into DLL (from lua) - this will bring major changes to the lua script and maybe application. I'm waiting for the final pull request of that. 
Once I have it , I will need to integrate everything into dev - which will be a little bit of play.

Let's keep fingers crossed for the Dll to work - then we shall see huge performance improvement and open window for new features as we will be working outside main game loop. :)

**Comment by davidp57** [comment]
Ah, I didn't understand what you said in #50 then !
I simply thought the "communication" part of the Windows app was going to be multithreaded.
Do you mean that the lua hook will be replaced by a dll library running in DCS ?

**Comment by szporwolik** [comment]
Yes, all the heavy stuff shall go into DLL - this is similar to how SRS/LotATC are handling it. 

Lua is single threaded - if your stuff takes too much time, you are dropping server frame rate and creating huge de-syncs, rubberbanding etc. While creating this app I was not really aware that whatever happens in the "onSimulationFrame" is part of the main game loop, it's crazy, but... this is DCS.

**Comment by davidp57** [comment]
That's incredibly great ! 
Could you please point me in the right direction, I'd like to know more about developping DLLs for DCS ?

**Comment by szporwolik** [comment]
Well honestly speaking if I would be familiar with that I would do it already a long time ago. :)

Luckily I was able to get with one of my colleges, who is much familiar with the multi threaded C stuff and who took the challenge.

As mentioned, let's wait for him - once he succeeds we will have the code in the repo and material for training. :)

**Comment by davidp57** [comment]
Ok, fair enough.
Can't wait, both for having a more efficient Perun on our server, and for learning how to do a DLL for DCS (got loooooooots of ideas in my tiny head)

**Comment by szporwolik** [comment]
Yep, everybody wants to have the access to the game state via SQL! I'm on the hype train as well. :D

**Comment by szporwolik** [comment]
Merged, but the the minimize to try does not seem to work (?). @davidp57 does it work for you ?

Great thanks!

**Comment by davidp57** [comment]
> Merged, but the the minimize to try does not seem to work (?). @davidp57 does it work for you ?
> 
> Great thanks!

Well, now that you say so I checked (never used it except in debugging, actually) and the app closes but the process is still there.
Sorry for the mess !

**Comment by szporwolik** [comment]
No problem, that's what dev branch is for. :)

**Comment by davidp57** [comment]
corrected in PR #56

**Pull request merged**
